//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 04:32:27 PM CET 
//


package com.epam.junior.zip_to_svg.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.junior.zip_to_svg.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zips_QNAME = new QName("http://www.epam.com/training/zip", "zips");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.junior.zip_to_svg.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZipListType }
     * 
     */
    public ZipListType createZipListType() {
        return new ZipListType();
    }

    /**
     * Create an instance of {@link ZipRecordType }
     * 
     */
    public ZipRecordType createZipRecordType() {
        return new ZipRecordType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZipListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.epam.com/training/zip", name = "zips")
    public JAXBElement<ZipListType> createZips(ZipListType value) {
        return new JAXBElement<ZipListType>(_Zips_QNAME, ZipListType.class, null, value);
    }

}
