//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 04:32:27 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.epam.com/training/zip", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epam.junior.ziptosvg.domain;
