//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 04:32:27 PM CET 
//


package com.epam.junior.ziptosvg.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.epam.junior.ziptosvg.utils.HtmlUtils;


/**
 * <p>Java class for ZipRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZipRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zip" type="{http://www.epam.com/training/zip}ZipType"/>
 *         &lt;element name="latitude" type="{http://www.epam.com/training/zip}CoordinateType" minOccurs="0"/>
 *         &lt;element name="longitude" type="{http://www.epam.com/training/zip}CoordinateType" minOccurs="0"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.epam.com/training/zip}StateType"/>
 *         &lt;element name="county" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zip-class" type="{http://www.epam.com/training/zip}ZipClassType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZipRecordType", propOrder = {
    "zip",
    "latitude",
    "longitude",
    "city",
    "state",
    "county",
    "zipClass"
})
public class ZipRecordType {
	
	private static final BigDecimal _800 = BigDecimal.valueOf(800);
	private static final BigDecimal _10 = BigDecimal.valueOf(10);
	private static final BigDecimal _2000 = BigDecimal.valueOf(2000);

    @XmlSchemaType(name = "integer")
    protected int zip;
    protected BigDecimal latitude;
    protected BigDecimal longitude;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String state;
    protected String county;
    @XmlElement(name = "zip-class", required = true)
    @XmlSchemaType(name = "string")
    protected ZipClassType zipClass;

    /**
     * Gets the value of the zip property.
     * 
     */
    public int getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     */
    public void setZip(int value) {
        this.zip = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the zipClass property.
     * 
     * @return
     *     possible object is
     *     {@link ZipClassType }
     *     
     */
    public ZipClassType getZipClass() {
        return zipClass;
    }

    /**
     * Sets the value of the zipClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZipClassType }
     *     
     */
    public void setZipClass(ZipClassType value) {
        this.zipClass = value;
    }
    
    public String createCircleTag(String color) {
    	if (latitude == null || longitude == null) {
    		return "";
    	}
    	
		StringBuilder sb = new StringBuilder();
		sb.append(HtmlUtils.printIdentation(3) + "<circle cy=\"");
		sb.append(getCY());
		sb.append("\" cx=\"");
		sb.append(getCX());
		sb.append("\" fill=\"" + color + "\" r=\"1\"/>" + System.lineSeparator());
    	
    	return sb.toString();
    }
    
    private BigDecimal getCY() {
    	return _800.subtract(latitude.multiply(_10));
	}

	private BigDecimal getCX() {
		return (longitude.multiply(_10)).add(_2000);
	}

}
